openapi: 3.0.1
info:
  title: Bin
  description: Ok bin
  version: v2
servers:
  - url: https://apim-ricardoreyesm.azure-api.net/binsuf/v2
paths:
  /*:
    get:
      summary: WildcardGet
      operationId: wildcardget
      responses:
        '200':
          description: ''
  /get:
    get:
      tags:
        - GET
        - Estado
      summary: FetchData
      description: Op get
      operationId: fetchdata
      responses:
        '200':
          description: ''
  '/status/{code}':
    get:
      summary: GetStatus
      operationId: getstatus
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]